#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin: "mint" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-remote-theme 
  - jekyll-include-cache # add this line to the plugins list if you already have one
  - jekyll-paginate

title: thananes.github.io

defaults:
  - scope:
      path: "_images"
    values:
      image: true
    # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
    - scope:
      path: "/estudios/"
      type: posts
    values:
      layout: single

collections:
  members:
    output: true



# número de posts por página
paginate: 2
paginate_path: /blog/page:num/



minima:
  skin: dark

name: thananes.github.io
  
